let a=6;
let b=4;
let zbir= a+b;
let razlika= a-b;
let proizvod = a*b;
let kolicnik= a/b;
let ostatak= a%b;
let stepen = Math.pow(a,b);
console.log (`Zbir je ${zbir}`);
console.log (`Razlika je ${razlika}`);
console.log (`Proizvod je ${proizvod}`);
console.log (`Kolicnik je ${kolicnik}`);
console.log (`Ostatak pri deljenju je ${ostatak}`);
console.log (`Stepen je ${stepen}`);
